apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-samhandling-proxy-fss-q2"
  namespace: "pensjonsamhandling"
  labels:
    "team": "pensjonsamhandling"
spec:
  webproxy: true # Inject on-premises web proxy configuration into the application pod, trengs i on-prem apps
  env:
    - name: PEN_SCOPE
      value: api://dev-fss.teampensjon.pensjon-pen-q2/.default
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev.adeo.no/pen/springapi
    - name: KRIGSPENSJON_GROUP_ID
      value: {{krigspensjonGroupId}}
    - name: MASKINPORTEN_ISSUER
      value: "https://test.maskinporten.no/"
  accessPolicy:
    inbound:
      rules:
        - application: afp-privat
          namespace: pensjon-saksbehandling
          cluster: dev-gcp
          permissions:
            roles:
              - afp-privat
        - application: pensjon
          namespace: aap
          cluster: dev-gcp
          permissions:
            roles:
              - aap
        - application: pensjon-krigspensjon-api
          namespace: pensjon-saksbehandling
          cluster: dev-gcp
          permissions:
            scopes:
              - krigspensjon
        - application: ida
          namespace: traktor
          cluster: prod-fss
  image: {{image}}
  liveness:
    path: "/actuator/health/liveness"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/actuator/health/readiness"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/actuator/prometheus"
  resources:
    limits:
      cpu: "10"
      memory: "256Mi"
    requests:
      cpu: "1"
      memory: "256Mi"
  ingresses:
    - https://pensjon-pen-proxy-fss-q2.dev-fss-pub.nais.io
    - https://pensjon-pen-proxy-fss-q2.dev.intern.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: {{krigspensjonGroupId}}