name: "Build and deploy pensjon-samhandling-proxy-fss"
on:
  push:
    branches:
    - "main"
    - "dev"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "gradle/wrapper-validation-action@v1"
    - uses: "actions/cache@v2"
      with:
        "path": "~/.gradle/caches"
        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
        "restore-keys": "${{ runner.os }}-gradle-"
    - uses: "actions/setup-java@v1"
      with:
        "java-version": "18"
    - name: "compile and run tests"
      run: "./gradlew build"
    - name: "Login to GitHub Docker Registry"
      uses: "docker/login-action@v2"
      with:
        "registry": "ghcr.io"
        "username": "${{ github.actor }}"
        "password": "${{ secrets.GITHUB_TOKEN }}"
    - name: "Build and push the Docker image"
      run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"
#  "deployAppToQ1":
#    name: "Deploy q1-app to dev-fss"
#    needs: "build"
#    runs-on: "ubuntu-latest"
#    steps:
#      - uses: "actions/checkout@v3"
#      - name: "Deploy q1-app to DEV-FSS"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "dev-fss"
#          "RESOURCE": ".nais/deploy-q1.yaml"
#          "VARS": ".nais/env-q1.yaml"
#  "deployAppToQ2":
#    name: "Deploy q2-app to dev-fss"
#    needs: "build"
#    runs-on: "ubuntu-latest"
#    steps:
#      - uses: "actions/checkout@v3"
#      - name: "Deploy q2-app to DEV-FSS"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "dev-fss"
#          "RESOURCE": ".nais/deploy-q2.yaml"
#          "VARS": ".nais/env-q2.yaml"
#  "deployAppToProd":
#    name: "Deploy app to prod"
#    needs: "deployAppToQ2"
#    if: github.ref == 'refs/heads/main'
#    runs-on: "ubuntu-latest"
#    steps:
#    - uses: "actions/checkout@v3"
#    - name: "Deploy to PROD"
#      uses: "nais/deploy/actions/deploy@v1"
#      env:
#        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#        "CLUSTER": "prod-fss"
#        "RESOURCE": ".nais/deploy-prod.yaml"
#        "VARS": ".nais/env-prod.yaml"